name: Go

on: [ push, pull_request ]

jobs:

  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Build
      run: cd $GITHUB_HEAD_REF  && go build .

    - name: Test
      run:  cd $GITHUB_HEAD_REF  && go test .

  lint:
    runs-on: golangci/golangci-lint:v1.43.0
    steps:

    - uses: actions/checkout@v2

    - name: Lint
      run: cd $GITHUB_HEAD_REF  && golangci-lint run -v
