name: Go

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Build
      run: pwd && ls -alt && cd $GITHUB_HEAD_REF  && go build .

    - name: Test
      run:  pwd && ls -alt && cd $GITHUB_HEAD_REF  && go test .